# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Michelle Wang | Data Science Blog
description: >- # this means to ignore newlines until "baseurl:"
  Michelle Wang's Github Blog  
baseurl: "" # the subpath of the site
url: "https://michelle-wms.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Words
    - name: Portfolio

footer:
  # show_powered_by: true
  contact:
    - name: Email
      value: mozzerellanu@gmail.com
      link: mailto:mozzerellanu@gmail.com

  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/michelle-w-5a2b6317/
    - name: GitHub
      link: https://github.com/michelle-wms
  

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
